analytics: {}
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.274774
  lightness: 0.418918
  rhythmicContrast: 0.613738
  saturation: 0.614864
cta: {}
layout_spectrum: 0.5550734668501148
name: coledowden
opengraph: {}
purpose: {}
typography_spectrum: 0.8642280893848007
